# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.schema.json

PackageIdentifier: zxzchocolate.NovaDrive
PackageVersion: 1.0.0
DefaultLocale: en-US
ManifestType: defaultLocale
ManifestVersion: 1.10.0
