# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.schema.json

PackageIdentifier: zxzchocolate.NovaDrive
PackageVersion: 1.0.0

Installers:
  - Architecture: x64
    InstallerType: exe
    InstallerUrl: https://zxzchocolate.github.io/NovaDriveInstaller/install.cmd
    InstallerSha256: REPLACE_WITH_SHA256

ManifestType: installer
ManifestVersion: 1.10.0
