# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.schema.json

PackageIdentifier: zxzchocolate.NovaDrive
PackageVersion: 1.0.0

PackageLocale: en-US

Publisher: zxzchocolate
PublisherUrl: https://github.com/zxzchocolate

PackageName: NovaDrive
PackageUrl: https://zxzchocolate.github.io/NovaDriveInstaller/

License: MIT
ShortDescription: Terminal-based Puter cloud drive client.
Description: Terminal-based NovaDrive client for accessing Puter cloud storage from Windows.

Tags:
  - puter
  - cloud
  - drive
  - terminal
  - novadrive

ManifestType: defaultLocale
ManifestVersion: 1.10.0
